# Generated by Django 3.2 on 2021-09-24 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ScreeningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('website', models.URLField()),
                ('partner_desc', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('subdomain', models.CharField(blank=True, max_length=100)),
                ('thankyou_template', models.CharField(blank=True, max_length=500)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('focus_area', models.TextField()),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ScreeningApp.candidate')),
                ('availability', models.CharField(choices=[('0 - 10 hours per week', '0 - 10 hours per week'), ('10 - 20 hours per week', '10 - 20 hours per week'), ('20 - 30 hours per week', '20 - 30 hours per week'), ('30 - 40 hours per week', '30 - 40 hours per week')], max_length=100)),
                ('current_occupation', models.CharField(choices=[('Student', 'Student'), ('Working Professional', 'Working Professional'), ('Government Official', 'Government Official')], max_length=200)),
                ('years_of_experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1+ years', '1+ years'), ('2+ years', '2+ years'), ('3+ years', '3+ years'), ('5+ years', '5+ years'), ('10+ years', '10+ years'), ('15+ years', '15+ years'), ('20+ years', '20+ years')], max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFC.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
            bases=('ScreeningApp.candidate',),
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=500)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('auth_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFC.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'Team_Member',
                'verbose_name_plural': 'Team_Members',
            },
        ),
    ]
