# Generated by Django 3.2 on 2021-09-24 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('highest_education', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=50)),
                ('level_of_expertise', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=100)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('expertise_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=300)),
                ('is_published', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertises',
            },
        ),
        migrations.CreateModel(
            name='Expertise_Area',
            fields=[
                ('expertise_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_of_expertise', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Expertise_Area',
                'verbose_name_plural': 'Expertise_Areas',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('qtype', models.CharField(choices=[('multiple choice', 'Multiple Choice'), ('yes/no', 'Yes/No')], max_length=100)),
                ('question', models.TextField()),
                ('option_1', models.TextField(blank=True, null=True)),
                ('option_2', models.TextField(blank=True, null=True)),
                ('option_3', models.TextField(blank=True, null=True)),
                ('option_4', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, choices=[('option_1', 'option_1'), ('option_2', 'option_2'), ('option_3', 'option_3'), ('option_4', 'option_4')], max_length=100, null=True)),
                ('question_img', models.URLField(blank=True, null=True)),
                ('category_of_expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.expertise_area')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.expertise')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Screenings',
            fields=[
                ('screening_id', models.AutoField(primary_key=True, serialize=False)),
                ('screening_uuid', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Open', max_length=50)),
                ('screening_result', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('first_reminder_date', models.DateField(blank=True, null=True)),
                ('second_reminder_date', models.DateField(blank=True, null=True)),
                ('third_reminder_date', models.DateField(blank=True, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.candidate', verbose_name='Candidate Name')),
            ],
            options={
                'verbose_name': 'Screening',
                'verbose_name_plural': 'Screenings',
            },
        ),
        migrations.CreateModel(
            name='Screenings_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_ans', models.CharField(blank=True, max_length=50)),
                ('correct_ans', models.CharField(blank=True, max_length=50)),
                ('answer_correctness', models.CharField(blank=True, max_length=10)),
                ('question', models.ManyToManyField(related_name='questions', to='ScreeningApp.Question')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.screenings', verbose_name='candidate_name')),
            ],
            options={
                'verbose_name': 'Screening_Question',
                'verbose_name_plural': 'Screenings_Questions',
            },
        ),
        migrations.AddField(
            model_name='expertise',
            name='category_of_expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.expertise_area'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='area_of_expertise',
            field=models.ManyToManyField(to='ScreeningApp.Expertise'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.expertise_area'),
        ),
    ]
